[package]
name = "aurora"
version = "0.1.0"
edition = "2021"

[dependencies]
vosk = "0.3.1"
cpal = "0.17.3"
anyhow = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
colored = "3.1.1"
open = "5"
